#!/usr/bin/python3
"""
%(prog)s

Start Tmux and connect to active test-functional VM hosts.
"""
import re
import os
import sys
import argparse
import subprocess
import tempfile
from pathlib import Path

def main():
    p = argparse.ArgumentParser(usage=__doc__.strip())
    args = p.parse_args()

    sockets = []

    tmpdir = Path(tempfile.gettempdir())
    for d in tmpdir.iterdir():
        if not d.name.startswith("bluez-func-test-"):
            continue

        for s in d.iterdir():
            if s.name.startswith("bluez-func-test-tty-"):
                sockets.append(s)

    if not sockets:
        print(f"No sockets in {tmpdir} to attach to")
        return

    session = "bluez-func-test"

    for j, sock in enumerate(sockets):
        name = re.sub(r".*tty-", "host", sock.name)

        cmd = ["tmux"]
        if j == 0:
            cmd += ['new-session', '-d', '-n', name, "-s", session]
        else:
            cmd += ['new-window', '-d', '-n', name, "-t", f"{session}:"]
        cmd += ["--", "socat", sock, "STDIO,rawer"]

        subprocess.run(cmd, check=True)

    os.execvp("tmux", ["tmux", "attach-session", "-t", session])

if __name__ == "__main__":
    main()
    sys.exit(0)
