#!/bin/sh

if [ -f config.status ]; then
	make maintainer-clean
fi

if [ ! -f doc/gtk-doc.make ]; then
	gtkdocize --copy --docdir doc
fi

./bootstrap && \
    ./configure --enable-maintainer-mode \
		--enable-debug \
		--prefix=/usr \
		--mandir=/usr/share/man \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--libexecdir=/lib \
		--enable-capng \
		--enable-gatt-example \
		--enable-proximity \
		--enable-time \
		--enable-alert \
		--enable-health \
		--enable-tracer \
		--enable-tools \
		--enable-bccmd \
		--enable-dfutool \
		--enable-hid2hci \
		--enable-hidd \
		--enable-pand \
		--enable-dund \
		--enable-test \
		--enable-cups \
		--enable-dbusoob \
		--enable-maemo6 \
		--enable-pnat \
		--enable-sap \
		--enable-thermometer \
		--enable-wiimote \
		--disable-pcmcia \
		--disable-datafiles $*
