if MESH
mesh_sources = mesh/mesh.h mesh/mesh.c \
				mesh/mesh-io.h mesh/mesh-io.c \
				mesh/mesh-io-api.h \
				mesh/mesh-io-generic.h \
				mesh/mesh-io-generic.c \
				mesh/storage.h mesh/storage.c \
				mesh/net.h mesh/net.c \
				mesh/display.h mesh/display.c \
				mesh/crypto.h mesh/crypto.c \
				mesh/friend.h mesh/friend.c \
				mesh/appkey.c \
				mesh/node.h mesh/node.c \
				mesh/prov.h mesh/prov.c \
				mesh/provision.h mesh/provision.c \
				mesh/model.h mesh/model.c \
				mesh/cfgmod.h mesh/cfgmod-server.c \
				mesh/mesh-db.h mesh/mesh-db.c \
				mesh/util.h mesh/util.c \
				mesh/mesh-defs.h
libexec_PROGRAMS += mesh/meshd

mesh_meshd_SOURCES = $(mesh_sources) mesh/main.c

mesh_meshd_LDADD = src/shared/ecc.lo src/shared/queue.lo src/shared/io-ell.lo \
				src/shared/util.lo src/shared/hci.lo src/shared/mgmt.lo \
				@DBUS_LIBS@ @ELL_LIBS@ -ljson-c

noinst_PROGRAMS += mesh/btmesh

mesh_btmesh_SOURCES = $(mesh_sources) \
						mesh/agent.h \
						mesh/agent.c \
						mesh/btmesh.c

mesh_btmesh_LDADD = src/shared/ecc.lo src/shared/queue.lo src/shared/io-ell.lo \
				src/shared/util.lo src/shared/hci.lo src/shared/mgmt.lo \
				src/libshared-mainloop.la \
				-lreadline @ELL_LIBS@ -ljson-c

endif
