if MESH

mesh_sources = mesh/mesh.h mesh/mesh.c \
				mesh/net_keys.h mesh/net_keys.c \
				mesh/mesh-io.h mesh/mesh-io.c \
				mesh/error.h mesh/mesh-io-api.h \
				mesh/mesh-io-generic.h \
				mesh/mesh-io-generic.c \
				mesh/storage.h mesh/storage.c \
				mesh/net.h mesh/net.c \
				mesh/crypto.h mesh/crypto.c \
				mesh/friend.h mesh/friend.c \
				mesh/appkey.h mesh/appkey.c \
				mesh/node.h mesh/node.c \
				mesh/provision.h mesh/prov.h \
				mesh/model.h mesh/model.c \
				mesh/cfgmod.h mesh/cfgmod-server.c \
				mesh/mesh-db.h mesh/mesh-db.c \
				mesh/util.h mesh/util.c \
				mesh/dbus.h mesh/dbus.c \
				mesh/agent.h mesh/agent.c \
				mesh/prov-acceptor.c mesh/prov-initiator.c \
				mesh/pb-adv.h mesh/pb-adv.c \
				mesh/mesh-defs.h
libexec_PROGRAMS += mesh/meshd

mesh_meshd_SOURCES = $(mesh_sources) mesh/main.c
mesh_meshd_LDADD = src/libshared-ell.la $(ell_ldadd) -ljson-c
mesh_meshd_DEPENDENCIES = $(ell_dependencies) src/libshared-ell.la
endif
