
builtin_modules += service
builtin_sources += plugins/service.c

builtin_modules += formfactor
builtin_sources += plugins/formfactor.c

builtin_modules += adaptername
builtin_sources += plugins/adaptername.c

builtin_modules += gatt_example
builtin_sources += plugins/gatt-example.c

builtin_modules += wiimote
builtin_sources += plugins/wiimote.c

if EXPERIMENTAL
builtin_modules += dbusoob
builtin_sources += plugins/dbusoob.c

builtin_modules += neard
builtin_sources += plugins/neard.c
endif
