.\" 
.TH "HCID" "8" "March 2004" "hcid - HCI daemon" "System management commands"
.SH "NAME"
hcid \- Bluetooth Host Controller Interface Daemon

.SH "SYNOPSIS"
.B hcid
[
.B \-n
] [
.B \-f
.I config\-file
]

.SH "DESCRIPTION"
This manual page documents briefly the
.B hcid
daemon, which manages all the Bluetooth devices. 
.B hcid
itself does not accept many command\-line options, as most of its
configuration is done in the 
.B hcid.conf
file, which has its own man page.
.SH "OPTIONS"
.TP 
.B \-n
Don't fork to run daemon in background.
.TP 
.BI \-f\ config\-file
Use alternate configuration file instead of /etc/bluetooth/hcid.conf
.SH "FILES"
.TP 
.I /etc/bluetooth/hcid.conf
Default location of the global configuration file.

.SH "SEE ALSO"
\fBhcid.conf\fR(5)
.SH "AUTHOR"
This manual page was written by Philipp Matthias Hahn.
