#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.bluez', '/org/bluez'),
							'org.bluez.Manager')

conn = manager.ActivateService('network')

network = dbus.Interface(bus.get_object(conn, '/org/bluez/network'),
						'org.bluez.network.Manager')

try:
	nap = dbus.Interface(bus.get_object('org.bluez.network',
					network.FindAdapter('nap')),
						'org.bluez.network.Server')
except:
	pass

try:
	gn = dbus.Interface(bus.get_object('org.bluez.network',
					network.FindAdapter('gn')),
						'org.bluez.network.Server')
except:
	pass
