#!/usr/bin/python

import time
import dbus

bus = dbus.SystemBus()

xml = ' \
<?xml version="1.0" encoding="UTF-8" ?> 	\
<record>					\
  <attribute id="0x0001">			\
    <sequence>					\
      <uuid value="0x1101"/>			\
    </sequence>					\
  </attribute>					\
  <attribute id="0x0004">			\
    <sequence>					\
      <sequence>				\
        <uuid value="0x0100"/>			\
      </sequence>				\
      <sequence>				\
        <uuid value="0x0003"/>			\
        <uint8 value="23" name="channel"/>	\
      </sequence>				\
    </sequence>					\
  </attribute>					\
  <attribute id="0x0100">			\
    <text value="COM5" name="name"/>		\
  </attribute>					\
</record>					\
'

database = dbus.Interface(bus.get_object('org.bluez', '/org/bluez'),
							'org.bluez.Database')

handle = database.AddServiceRecordFromXML(xml)

print "Service record with handle 0x%04x added" % (handle)

print "Press CTRL-C to remove service record"

try:
	time.sleep(1000)
	print "Terminating session"
except:
	pass

database.RemoveServiceRecord(handle)
