#!/bin/sh
#
#  Create Bluetooth devices in /dev
#

VHCI_MAJOR=10
VHCI_MINOR=250

RFCOMM_MAJOR=216

#
# Create device for VHCI
#
if [ ! -c /dev/vhci ]; then
	mknod /dev/vhci c ${VHCI_MAJOR} ${VHCI_MINOR}
	chmod 664 /dev/vhci
fi

#
# Create devices for RFCOMM
#
for i in `seq 0 255`
do
	if [ ! -c /dev/rfcomm$i ]; then
		mknod -m 666 /dev/rfcomm$i c ${RFCOMM_MAJOR} $i
	fi
done
