.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\"
.TH HID2HCI 8 "JUNE 6, 2003" "" ""

.SH NAME
hid2hci \- Bluetooth HID to HCI mode switching utility
.SH SYNOPSIS
.BR "hid2hci
[
.I options
]
.SH DESCRIPTION
.B hid2hci
is used to set up switch HID proxy Bluetooth dongle into the HCI
mode and back.
.SH OPTIONS
.TP
.BI -h
Gives a list of possible options.
.TP
.BI -q
Don't display any messages.
.TP
.BI -0
Switches the device into HCI mode.
.TP
.BI -1
Switches the device into HID mode.
.SH AUTHOR
Written by Marcel Holtmann <marcel@holtmann.org>.
.br
